#!/usr/bin/python3

#
# Copyright (C) 2020-2021 Soleta Networks <info@soleta.eu>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the
# Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.

import json
import logging
import subprocess
try:
	from signal import SIG_DFL, SIGPIPE
except ImportError:
	from signal import SIG_DFL


from src.ogClient import *


def main():
	config_path = f'{ogClient.OG_PATH}ogclient/cfg/ogclient.json'
	try:
		with open(config_path, 'r') as f:
			CONFIG = json.load(f)
	except:
		print('Error: Parsing configuration file')
		return 0

	MODE = CONFIG['opengnsys']['mode']
	URL = CONFIG['opengnsys']['url']
	if MODE == 'live':
		proc = subprocess.Popen(["browser", "-qws", URL])
	if MODE != 'windows':
		signal.signal(SIGPIPE, SIG_DFL)

	client = ogClient(config=CONFIG)
	client.connect()
	client.run()

if __name__ == "__main__":
	main()
